import { AppState } from './types';

export const initialAppState: AppState = {
  institution: {
    name: 'مدرسة المسيرة الخضراء الابتدائية',
    directorate: 'المديرية الإقليمية لمراكش',
    academicYear: '2024-2025',
    directorName: 'ذ. عبد الرحيم العلمي',
    activeLevels: [
      'المستوى الأول',
      'المستوى الثاني',
      'المستوى الثالث',
      'المستوى الرابع',
      'المستوى الخامس',
      'المستوى السادس',
    ],
  },
  settings: {
    evaluationSystem: 'acquired_levels',
    theme: 'light',
    autoSave: true,
  },
  teachers: [
    {
      id: 't-1',
      name: 'ذ. محمد العلوي',
      code: 'ENS-0142',
      specialty: 'اللغة العربية',
      assignedLevel: 'المستوى الأول',
      phone: '0661123456',
    },
    {
      id: 't-2',
      name: 'أستاذة مريم المنصوري',
      code: 'ENS-0288',
      specialty: 'الرياضيات واللغة الفرنسية',
      assignedLevel: 'المستوى الأول',
      phone: '0662234567',
    },
    {
      id: 't-3',
      name: 'ذ. يوسف التازي',
      code: 'ENS-0315',
      specialty: 'اللغة العربية والتربية الإسلامية',
      assignedLevel: 'المستوى الثاني',
      phone: '0663345678',
    },
    {
      id: 't-4',
      name: 'أستاذة فاطمة الزهراء الإدريسي',
      code: 'ENS-0459',
      specialty: 'اللغة الفرنسية والنشاط العلمي',
      assignedLevel: 'المستوى الثاني',
      phone: '0664456789',
    },
    {
      id: 't-5',
      name: 'ذ. حسن العمراني',
      code: 'ENS-0501',
      specialty: 'الرياضيات',
      assignedLevel: 'المستوى الثالث',
      phone: '0665567890',
    },
  ],
  classes: [
    { id: 'c-1-1', level: 'المستوى الأول', name: 'الفوج 1', categoryCount: 3 },
    { id: 'c-1-2', level: 'المستوى الأول', name: 'الفوج 2', categoryCount: 2 },
    { id: 'c-2-1', level: 'المستوى الثاني', name: 'الفوج 1', categoryCount: 3 },
    { id: 'c-3-1', level: 'المستوى الثالث', name: 'الفوج 1', categoryCount: 3 },
  ],
  categories: [
    { id: 'cat-1-1-1', classId: 'c-1-1', level: 'المستوى الأول', name: 'الفئة 1' },
    { id: 'cat-1-1-2', classId: 'c-1-1', level: 'المستوى الأول', name: 'الفئة 2' },
    { id: 'cat-1-1-3', classId: 'c-1-1', level: 'المستوى الأول', name: 'الفئة 3' },
    { id: 'cat-1-2-1', classId: 'c-1-2', level: 'المستوى الأول', name: 'الفئة 1' },
    { id: 'cat-1-2-2', classId: 'c-1-2', level: 'المستوى الأول', name: 'الفئة 2' },
    { id: 'cat-2-1-1', classId: 'c-2-1', level: 'المستوى الثاني', name: 'الفئة 1' },
    { id: 'cat-2-1-2', classId: 'c-2-1', level: 'المستوى الثاني', name: 'الفئة 2' },
    { id: 'cat-2-1-3', classId: 'c-2-1', level: 'المستوى الثاني', name: 'الفئة 3' },
    { id: 'cat-3-1-1', classId: 'c-3-1', level: 'المستوى الثالث', name: 'الفئة 1' },
    { id: 'cat-3-1-2', classId: 'c-3-1', level: 'المستوى الثالث', name: 'الفئة 2' },
    { id: 'cat-3-1-3', classId: 'c-3-1', level: 'المستوى الثالث', name: 'الفئة 3' },
  ],
  tasks: [
    {
      id: 'task-1',
      teacherId: 't-1',
      taskType: 'examiner',
      level: 'المستوى الأول',
      classId: 'c-1-1',
      categoryId: 'cat-1-1-1',
      subjects: ['sub-ar', 'sub-math'],
      scopeNotes: 'تمرير رائز التشخيص لفوج 1 فئة 1 في القاعة 3',
    },
    {
      id: 'task-2',
      teacherId: 't-2',
      taskType: 'examiner',
      level: 'المستوى الأول',
      classId: 'c-1-1',
      categoryId: 'cat-1-1-2',
      subjects: ['sub-ar', 'sub-fr', 'sub-math'],
      scopeNotes: 'تمرير الرائز لفوج 1 فئة 2 في القاعة 4',
    },
    {
      id: 'task-3',
      teacherId: 't-3',
      taskType: 'examiner',
      level: 'المستوى الأول',
      classId: 'c-1-1',
      categoryId: 'cat-1-1-3',
      subjects: ['sub-ar', 'sub-math'],
      scopeNotes: 'تمرير الرائز لفوج 1 فئة 3 في القاعة 5',
    },
    {
      id: 'task-4',
      teacherId: 't-5',
      taskType: 'supervisor',
      level: 'المستوى الأول',
      scopeNotes: 'الإشراف وتتبع وتنسيق عمليات التمرير على صعيد المستوى الأول كاملاً',
    },
    {
      id: 'task-5',
      teacherId: 't-4',
      taskType: 'data_entry',
      level: 'المستوى الأول',
      scopeNotes: 'مسؤولة رقمنة وضبط نتائج التمرير لجميع فئات المستوى الأول والثاني',
    },
  ],
  subjects: [
    {
      id: 'sub-ar',
      name: 'اللغة العربية',
      code: 'AR',
      levels: ['المستوى الأول', 'المستوى الثاني', 'المستوى الثالث'],
      criteria: [
        { id: 'cr-ar-1', code: 'C1', title: 'فهم المقروء والنص المستمع إليه', description: 'يحدد المعنى العام للنص البسيط ويجيب عن أسئلة الفهم المباشرة' },
        { id: 'cr-ar-2', code: 'C2', title: 'التعرف على الحروف والأصوات ومخارجها', description: 'يميز بين الصوامت والصوائت القصيرة والطويلة والتنوين' },
        { id: 'cr-ar-3', code: 'C3', title: 'التمييز بين الكلمات وقراءة المقاطع', description: 'يدمج المقاطع لتركيب كلمات وقراءتها بسلامة' },
        { id: 'cr-ar-4', code: 'C4', title: 'إنتاج جملة بسيطة ومفيدة', description: 'يرتب كلمات مشوشة لتكوين جملة صحيحة التركيب والمعنى' },
        { id: 'cr-ar-5', code: 'C5', title: 'الطلاقة وحسن الإلقاء الصوتي', description: 'يقرأ كلمات وجمل بسرعة مناسبة مع احترام علامات الترقيم' },
        { id: 'cr-ar-6', code: 'C6', title: 'الرسم الخطي والنقل السليم', description: 'يكتب حروفا وكلمات وفق قواعد الخط العربي وبوضوح تام' },
      ],
    },
    {
      id: 'sub-math',
      name: 'الرياضيات',
      code: 'MATH',
      levels: ['المستوى الأول', 'المستوى الثاني', 'المستوى الثالث'],
      criteria: [
        { id: 'cr-math-1', code: 'C1', title: 'قراءة وكتابة الأعداد تسمية وتمثيلاً', description: 'يقرأ ويكتب الأعداد الصحيحة المقررة بالأرقام والحروف' },
        { id: 'cr-math-2', code: 'C2', title: 'مقارنة وترتيب الأعداد باستعمال الرموز', description: 'يرتب تصاعديا وتنازليا ويستعمل الرموز > و < و =' },
        { id: 'cr-math-3', code: 'C3', title: 'إنجاز عمليتي الجمع والطرح دون احتفاظ', description: 'يضع وينجز عمليات حسابية عمودية وأفقية بدقة' },
        { id: 'cr-math-4', code: 'C4', title: 'حل وضعية مسألة بسيطة ذات خطوة واحدة', description: 'يختار العملية المناسبة لحل مسألة حياتية مبسطة' },
        { id: 'cr-math-5', code: 'C5', title: 'التموضع في الفضاء والتعرف على الأشكال', description: 'يميز المربع والمستطيل والمثلث ومفاهيم فوق/تحت/يمين/يسار' },
      ],
    },
    {
      id: 'sub-fr',
      name: 'اللغة الفرنسية',
      code: 'FR',
      levels: ['المستوى الأول', 'المستوى الثاني', 'المستوى الثالث'],
      criteria: [
        { id: 'cr-fr-1', code: 'C1', title: 'Reconnaissance des lettres et phonèmes', description: 'Identifier les voyelles et consonnes de base' },
        { id: 'cr-fr-2', code: 'C2', title: 'Lecture de syllabes et mots simples', description: 'Combiner consonnes et voyelles pour former des syllabes' },
        { id: 'cr-fr-3', code: 'C3', title: 'Compréhension de consignes orales', description: 'Comprendre et exécuter une consigne simple en classe' },
        { id: 'cr-fr-4', code: 'C4', title: 'Écriture et graphisme', description: 'Reproduire correctement les lettres en écriture cursive' },
      ],
    },
  ],
  students: [
    // Level 1 - Class 1 - Category 1 (10 students)
    { id: 'std-101', studentNumber: 'G13401', fullName: 'أحمد محمد البقالي', gender: 'M', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-1' },
    { id: 'std-102', studentNumber: 'G13402', fullName: 'سارة عبد الله الناصري', gender: 'F', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-1' },
    { id: 'std-103', studentNumber: 'G13403', fullName: 'يوسف رشيد الإدريسي', gender: 'M', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-1' },
    { id: 'std-104', studentNumber: 'G13404', fullName: 'فاطمة الزهراء بنسليمان', gender: 'F', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-1' },
    { id: 'std-105', studentNumber: 'G13405', fullName: 'عمر خالد المنبهي', gender: 'M', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-1' },
    { id: 'std-106', studentNumber: 'G13406', fullName: 'خديجة طارق المرابط', gender: 'F', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-1' },
    { id: 'std-107', studentNumber: 'G13407', fullName: 'حمزة كمال الداودي', gender: 'M', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-1' },
    { id: 'std-108', studentNumber: 'G13408', fullName: 'مريم نور الدين الصقلي', gender: 'F', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-1' },
    { id: 'std-109', studentNumber: 'G13409', fullName: 'أيوب عبد الحق الشنتوف', gender: 'M', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-1' },
    { id: 'std-110', studentNumber: 'G13410', fullName: 'إسراء سعيد الفاسي', gender: 'F', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-1' },

    // Level 1 - Class 1 - Category 2 (10 students)
    { id: 'std-111', studentNumber: 'G13411', fullName: 'محمد ياسين التازي', gender: 'M', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-2' },
    { id: 'std-112', studentNumber: 'G13412', fullName: 'زينب مراد الوردي', gender: 'F', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-2' },
    { id: 'std-113', studentNumber: 'G13413', fullName: 'علي مصطفى الحريزي', gender: 'M', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-2' },
    { id: 'std-114', studentNumber: 'G13414', fullName: 'آية عبد الرحيم الصالحي', gender: 'F', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-2' },
    { id: 'std-115', studentNumber: 'G13415', fullName: 'ياسين حاتم الزياني', gender: 'M', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-2' },
    { id: 'std-116', studentNumber: 'G13416', fullName: 'هبة بوشعيب الشاوي', gender: 'F', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-2' },
    { id: 'std-117', studentNumber: 'G13417', fullName: 'عبد الرحمن عماد الغزاوي', gender: 'M', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-2' },
    { id: 'std-118', studentNumber: 'G13418', fullName: 'سلمى أنس الفيلالي', gender: 'F', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-2' },
    { id: 'std-119', studentNumber: 'G13419', fullName: 'آدم سفيان السوسي', gender: 'M', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-2' },
    { id: 'std-120', studentNumber: 'G13420', fullName: 'دعاء رضوان الرميلي', gender: 'F', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-2' },

    // Level 1 - Class 1 - Category 3 (10 students)
    { id: 'std-121', studentNumber: 'G13421', fullName: 'إلياس جمال الكوهن', gender: 'M', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-3' },
    { id: 'std-122', studentNumber: 'G13422', fullName: 'ريم توفيق البوعناني', gender: 'F', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-3' },
    { id: 'std-123', studentNumber: 'G13423', fullName: 'معاذ عادل الزموري', gender: 'M', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-3' },
    { id: 'std-124', studentNumber: 'G13424', fullName: 'سلمى عبد المجيد العلمي', gender: 'F', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-3' },
    { id: 'std-125', studentNumber: 'G13425', fullName: 'بدر الدين كريم الركراكي', gender: 'M', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-3' },
    { id: 'std-126', studentNumber: 'G13426', fullName: 'أمينة نبيل الشرايبي', gender: 'F', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-3' },
    { id: 'std-127', studentNumber: 'G13427', fullName: 'سفيان يونس الجباري', gender: 'M', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-3' },
    { id: 'std-128', studentNumber: 'G13428', fullName: 'صفاء هشام البشيري', gender: 'F', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-3' },
    { id: 'std-129', studentNumber: 'G13429', fullName: 'أنس جلال المريني', gender: 'M', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-3' },
    { id: 'std-130', studentNumber: 'G13430', fullName: 'كنزة عصام المودن', gender: 'F', level: 'المستوى الأول', classId: 'c-1-1', categoryId: 'cat-1-1-3' },

    // Level 1 - Class 2 (sample students)
    { id: 'std-131', studentNumber: 'G13431', fullName: 'يحيى عبد الكريم البصري', gender: 'M', level: 'المستوى الأول', classId: 'c-1-2', categoryId: 'cat-1-2-1' },
    { id: 'std-132', studentNumber: 'G13432', fullName: 'نهيلة توفيق الزغاري', gender: 'F', level: 'المستوى الأول', classId: 'c-1-2', categoryId: 'cat-1-2-1' },
    { id: 'std-133', studentNumber: 'G13433', fullName: 'طه أمين العوفير', gender: 'M', level: 'المستوى الأول', classId: 'c-1-2', categoryId: 'cat-1-2-2' },
    { id: 'std-134', studentNumber: 'G13434', fullName: 'مروى عبد الصمد السبتي', gender: 'F', level: 'المستوى الأول', classId: 'c-1-2', categoryId: 'cat-1-2-2' },
  ],
  passingSheets: [
    {
      id: 'sheet-1',
      level: 'المستوى الأول',
      classId: 'c-1-1',
      categoryId: 'cat-1-1-1',
      teacherId: 't-1',
      subjectIds: ['sub-ar', 'sub-math'],
      passingDate: '2024-10-15',
      notes: 'تم التمرير في ظروف تربوية ملائمة وبانضباط تام للمتعلمين',
      status: 'completed',
    },
    {
      id: 'sheet-2',
      level: 'المستوى الأول',
      classId: 'c-1-1',
      categoryId: 'cat-1-1-2',
      teacherId: 't-2',
      subjectIds: ['sub-ar', 'sub-fr', 'sub-math'],
      passingDate: '2024-10-16',
      notes: 'ملاحظة تعثر بعض التلاميذ في التمييز بين الحروف المتشابهة',
      status: 'in_progress',
    },
    {
      id: 'sheet-3',
      level: 'المستوى الأول',
      classId: 'c-1-1',
      categoryId: 'cat-1-1-3',
      teacherId: 't-3',
      subjectIds: ['sub-ar', 'sub-math'],
      passingDate: '2024-10-16',
      notes: '',
      status: 'pending',
    },
    {
      id: 'sheet-4',
      level: 'المستوى الأول',
      classId: 'c-1-2',
      categoryId: 'cat-1-2-1',
      teacherId: 't-1',
      subjectIds: ['sub-ar', 'sub-math'],
      passingDate: '2024-10-17',
      notes: '',
      status: 'pending',
    },
  ],
  results: {
    // Student 101 - AR
    'std-101_sub-ar_C1': 'acquired',
    'std-101_sub-ar_C2': 'acquired',
    'std-101_sub-ar_C3': 'acquired',
    'std-101_sub-ar_C4': 'in_progress',
    'std-101_sub-ar_C5': 'acquired',
    'std-101_sub-ar_C6': 'acquired',
    // Student 101 - MATH
    'std-101_sub-math_C1': 'acquired',
    'std-101_sub-math_C2': 'acquired',
    'std-101_sub-math_C3': 'acquired',
    'std-101_sub-math_C4': 'acquired',
    'std-101_sub-math_C5': 'acquired',

    // Student 102 - AR (needs remediation in C2, C4)
    'std-102_sub-ar_C1': 'acquired',
    'std-102_sub-ar_C2': 'not_acquired',
    'std-102_sub-ar_C3': 'in_progress',
    'std-102_sub-ar_C4': 'not_acquired',
    'std-102_sub-ar_C5': 'in_progress',
    'std-102_sub-ar_C6': 'in_progress',
    // Student 102 - MATH
    'std-102_sub-math_C1': 'acquired',
    'std-102_sub-math_C2': 'acquired',
    'std-102_sub-math_C3': 'not_acquired',
    'std-102_sub-math_C4': 'not_acquired',
    'std-102_sub-math_C5': 'in_progress',

    // Student 103 - AR
    'std-103_sub-ar_C1': 'acquired',
    'std-103_sub-ar_C2': 'acquired',
    'std-103_sub-ar_C3': 'acquired',
    'std-103_sub-ar_C4': 'acquired',
    'std-103_sub-ar_C5': 'in_progress',
    'std-103_sub-ar_C6': 'acquired',
    // Student 103 - MATH
    'std-103_sub-math_C1': 'acquired',
    'std-103_sub-math_C2': 'acquired',
    'std-103_sub-math_C3': 'acquired',
    'std-103_sub-math_C4': 'acquired',
    'std-103_sub-math_C5': 'acquired',

    // Student 104 - AR (needs remediation in C1, C4, C5)
    'std-104_sub-ar_C1': 'not_acquired',
    'std-104_sub-ar_C2': 'acquired',
    'std-104_sub-ar_C3': 'in_progress',
    'std-104_sub-ar_C4': 'not_acquired',
    'std-104_sub-ar_C5': 'not_acquired',
    'std-104_sub-ar_C6': 'acquired',
    // Student 104 - MATH
    'std-104_sub-math_C1': 'in_progress',
    'std-104_sub-math_C2': 'not_acquired',
    'std-104_sub-math_C3': 'not_acquired',
    'std-104_sub-math_C4': 'not_acquired',
    'std-104_sub-math_C5': 'acquired',

    // Student 105 - AR
    'std-105_sub-ar_C1': 'acquired',
    'std-105_sub-ar_C2': 'acquired',
    'std-105_sub-ar_C3': 'acquired',
    'std-105_sub-ar_C4': 'acquired',
    'std-105_sub-ar_C5': 'acquired',
    'std-105_sub-ar_C6': 'acquired',
    // Student 105 - MATH
    'std-105_sub-math_C1': 'acquired',
    'std-105_sub-math_C2': 'acquired',
    'std-105_sub-math_C3': 'acquired',
    'std-105_sub-math_C4': 'in_progress',
    'std-105_sub-math_C5': 'acquired',

    // Student 106
    'std-106_sub-ar_C1': 'acquired',
    'std-106_sub-ar_C2': 'acquired',
    'std-106_sub-ar_C3': 'not_acquired',
    'std-106_sub-ar_C4': 'not_acquired',
    'std-106_sub-ar_C5': 'in_progress',
    'std-106_sub-ar_C6': 'acquired',

    // Student 107
    'std-107_sub-ar_C1': 'acquired',
    'std-107_sub-ar_C2': 'acquired',
    'std-107_sub-ar_C3': 'acquired',
    'std-107_sub-ar_C4': 'acquired',
    'std-107_sub-ar_C5': 'acquired',
    'std-107_sub-ar_C6': 'acquired',

    // Student 108
    'std-108_sub-ar_C1': 'in_progress',
    'std-108_sub-ar_C2': 'not_acquired',
    'std-108_sub-ar_C3': 'not_acquired',
    'std-108_sub-ar_C4': 'not_acquired',
    'std-108_sub-ar_C5': 'not_acquired',
    'std-108_sub-ar_C6': 'in_progress',

    // Student 109
    'std-109_sub-ar_C1': 'acquired',
    'std-109_sub-ar_C2': 'acquired',
    'std-109_sub-ar_C3': 'acquired',
    'std-109_sub-ar_C4': 'in_progress',
    'std-109_sub-ar_C5': 'acquired',
    'std-109_sub-ar_C6': 'acquired',

    // Student 110
    'std-110_sub-ar_C1': 'acquired',
    'std-110_sub-ar_C2': 'acquired',
    'std-110_sub-ar_C3': 'acquired',
    'std-110_sub-ar_C4': 'acquired',
    'std-110_sub-ar_C5': 'acquired',
    'std-110_sub-ar_C6': 'acquired',
  },
};
